name: supersetbot orglabel based on author

on:
  issues:
    types: [created, edited]

  pull_request:
    types: [created, edited]

jobs:
  superbot-orglabel:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:

      - name: Harden the runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup supersetbot
        uses: ./.github/actions/setup-supersetbot/

      - name: Execute supersetbot orglabel command
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Label the issue with the appropriate org using supersetbot
          # - this requires for the author to be publicly associated with their org
          # - and for the org to be listed in `supersetbot/src/metadata.js`
          supersetbot orglabel --issue ${{ github.event.number }} --repo ${{ github.repository }} || true
