name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
      with:
        use-policy-store: true
        egress-policy: audit
        api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

    - uses: actions/labeler@v5
      with:
        sync-labels: true

    # TODO: run scripts based on labels!
    # - id: run-translation-scripts
    #   if: contains(steps.label-the-PR.outputs.all-labels, 'i18n')
    #   run: |
    #     echo "Running translation scripts"
    #     # Generate .pot -> .po -> .json files
