name: Welcome New Contributor

on:
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          use-policy-store: true
          egress-policy: audit
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Welcome Message
        uses: actions/first-interaction@v1
        continue-on-error: true
        with:
          repo-token: ${{ github.token }}
          pr-message: |-
            Congrats on making your first PR and thank you for contributing to Superset! :tada: :heart:

            We hope to see you in our [Slack](https://apache-superset.slack.com/) community too! Not signed up? Use our [Slack App](http://bit.ly/join-superset-slack) to self-register.
